---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - litmuschaos.io
  resources:
  - chaosengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - litmuschaos.io
  resources:
  - chaosengines/finalizers
  verbs:
  - update
- apiGroups:
  - litmuschaos.io
  resources:
  - chaosengines/status
  verbs:
  - get
  - patch
  - update
