---
## This is the chaos engine resource requested by dev for the nginx 
## app, i.e., the user facing custom resource. Mapped to a dedicated
## controller which triggers the actual chaos experiments as per 
## defined schedule. The app developer is expected to annotate the
## application with litmuschaos.io/engine: <engine-name>

# chaosengine.yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: nginx-pod-delete
  namespace: default
spec:
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  auxiliaryAppInfo: ''
  monitoring: false
  appinfo: 
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=nginx'
    appkind: 'deployment'
  chaosServiceAccount: litmus
  experiments:
    - name: pod-delete
            
