---
## An experiment is the definition of a chaos test and is listed as an item 
## in the chaos engine to be run against a given app. Consists of reference
## to chaosGraph (which has chaos param details and executor spec) and also
## component information for the Object-Under-Test. The results upon running
## this experiment is relayed back to the chaos engine which invoked it.

## Experiments can be pulled from litmus charts and are versioned based on 
## chart.

## Charts should (not?) be auto-upgraded

apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:

  ## Eventually launched chaos litmusbook/job will bear <name>-<hash>
  name: pod-delete
  labels:
    litmuschaos.io/name: 
    litmuschaos.io/instance: 
    helm.sh/chart: 

description:
  message: |
    Deletes a pod belonging to a deployment/statefulset/daemonset

spec:

  ## A low-level definition of chaos parameters which is fed to the executor
  ## for running the experiment.

  ## Some experiments need more info on the "object of chaos". For example, in case 
  ## of container crash tests in a multi-container app, it is necessary to know both 
  ## general app info (namespace, labels) as well as container name which has to undergo
  ## failures. This Component info is generally kept to a minimum and passed as ENV to 
  ## the actual chaos-runner/executor pod/container.  

  definition:

    labels: 
      name: pod-delete

    image: 

    env:
      - name: ANSIBLE_STDOUT_CALLBACK
        value: ""

      ## Injected by chaosengine 
      - name: APP_NAMESPACE
        value: ""              

      ## Injected by chaosengine 
      - name: APP_LABEL         
        value: ""

      - name: FORCE_DELETE
        value: ""

      ## The chaos operator can use different execution frameworks to achieve
      ## to achieve a certain chaos operation. It could use Litmus or Chaostoolkit
      ## etc..,

      - name: LIB
        value: ""

    command: ["/bin/bash"]
    args: ["-c", "ansible-playbook ./experiments/chaos/pod_delete/test.yml -i /etc/ansible/hosts -vv; exit 0"]
