#!/bin/bash
set -e

if [ -z "${REPONAME}" ]
then
  REPONAME="litmuschaos"
fi

if [ -z "${IMGNAME}" ] || [ -z "${IMGTAG}" ] || [ -z "${IMGSHATAG}" ]
then
  echo "Image details are missing. Nothing to push.";
  exit 1
fi

IMAGEID=$( docker images -q ${REPONAME}/${IMGNAME}:${IMGTAG} )
IMAGESHAID=$( docker images -q ${REPONAME}/${IMGNAME}:${IMGSHATAG} )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  # Push image to docker hub
  echo "Pushing ${REPONAME}/${IMGNAME}:${IMGTAG} ...";
  docker push ${REPONAME}/${IMGNAME}:${IMGTAG} ;
  docker push ${REPONAME}/${IMGNAME}:${IMGSHATAG} ;
  if [ ! -z "${TRAVIS_TAG}" ] ;
  then
    # Push with different tags if tagged as a release
    # When github is tagged with a release, then Travis will 
    # set the release tag in env TRAVIS_TAG
    echo "Pushing ${REPONAME}/${IMGNAME}:${TRAVIS_TAG} ...";
    docker tag ${IMAGEID} ${REPONAME}/${IMGNAME}:${TRAVIS_TAG}
    docker push ${REPONAME}/${IMGNAME}:${TRAVIS_TAG};
    echo "Pushing ${REPONAME}/${IMGNAME}:latest ...";
    docker tag ${IMAGEID} ${REPONAME}/${IMGNAME}:latest
    docker push ${REPONAME}/${IMGNAME}:latest;
  fi;
else
  echo "No docker credentials provided. Skip uploading ${REPONAME}/${IMGNAME}:${IMGTAG} to docker hub";
fi;
