name: Push
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      - name: gofmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -ne 0 ]
          then
           echo "The following files were found to be not go formatted:"
           gofmt -s -l .
           exit 1
          fi

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1

      - name: unused-package check
        run: |
          make unused-package-check

  image-build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: login to GitHub Container Registry
        run: echo ${{ secrets.DPASS }} | docker login -u ${{ secrets.DNAME }} --password-stdin

      - name: Build & Push Docker Image
        env:
          DOCKER_REPO: litmuschaos
          DOCKER_IMAGE: chaos-operator
          DOCKER_TAG: ci
          DNAME: ${{ secrets.DNAME }}
          DPASS: ${{ secrets.DPASS }}
        run: |
          make push-chaos-operator

  tests:
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      #Install and configure a kind cluster
      - name: Installing Prerequisites (KinD Cluster)
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"

      - name: Configuring and testing the Installation
        run: |
          kubectl cluster-info --context kind-kind
          kind get kubeconfig --internal >$HOME/.kube/config
          kubectl get nodes

      - name: Dependency checks
        run: |
          make deps

      - name: Running Go BDD Test
        run: |
          make test

  security-scan:
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/litmuschaos/chaos-operator:ci'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'